project:
  type: website
  render: 
    - setup.md
    - "Workshops/*"
    - "Projects/*"

website:
  title: "Python Training Intensive"
  navbar:
    search: true
    left:
      - text: "Workshops"
        href: Workshops/index.qmd
      - text: "Project Gallery"
        href: Projects/project_gallery.qmd
  sidebar: 
    contents:
      - setup.md
      - auto: "Workshops"
      - section: The Project
        contents:
        - auto: "Projects/*"

format:
  html:
    theme: 
      - default
      - custom.scss
    toc: true
    embed-resources: false